name: CI/CD CIB-Contruction

on: 
    push:
        branches: [master]

jobs: 
    deploy:
        runs-on: ubuntu-latest 
        steps:
            - uses: actions/checkout@v5
            - name: Executes remote ssh commands
              uses: appleboy/ssh-action@v1.1.0
              with: 
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    # reaching the right directory
                    cd ${{ secrets.APP_PATH }}

                    # recuperation 
                    git pull origin master

                    # Installation des dépendances
                    composer install --no-dev --optimize-autoloader

                    # Actions Node directement sur le serveur
                    npm ci --no-audit --no-fund # --no-audit accélère le processus
                    npm run build

                    # Nettoyage pour libérer de la place et de la RAM
                    rm -rf node_modules

                    # Mise à jour de la base de données
                    php artisan migrate --force #--force pour éviter les intéractions
                    
                    # Netoyage
                    php artisan cache:clear
                    php artisan view:clear
                    php artisan route:clear
                    php artisan config:clear

                    # Mise en cache
                    php artisan optimize
                    php artisan filament:optimize


                    # Demarrage de la queue
                    php artisan queue:restart

                    #livewire
                    php artisan livewire:publish --assets
